uniswap-default.tokenlist.json
Please Add HUSD (stablecoin) to default token list
closes #219
Thank you.
=> Add HUSD token to the default list

src/tokens/mainnet.json, test/uniswap-default.test.js
Unit tests will fail because one token appears with duplicate symbol. discussing this offline and will update.
=> Add tokens and skip duplicate symbols unit test

src/buildList.js, src/tokens/mainnet.json, src/tokens/optimism.json, test/uniswap-default.test.js
- Updates default list with new set of tokens by adding them to mainnet.json
- Updates ANT token entry to use updated address
- To add OP token, I added a separate optimism.json file to source the details from since OP does not exist on mainnet. 
- Doubled unit test timeout due to larger list size.
=> add tokens to default list

src/tokens/mainnet.json
this PR adds SOCKS token to default list
=> add SOCKS token

.github/workflows/deploy.yaml
reference PR: https://github.com/Uniswap/interface/pull/5254
=> Switch deploy to use web3 gateway

src/buildList.js, src/tokens/sepolia.json
Mimicking the style of the goerli file
[Sepolia WETH](https://sepolia.etherscan.io/token/0x7b79995e5f793a07bc00c21412e50ecae098e7f9)
[Sepolia Uni](https://sepolia.etherscan.io/address/0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984)
=> Add Sepolia WETH and Uni

package.json, yarn.lock
=> feat: bump token-list-bridge-utils for avax addition

src/buildList.js, src/tokens/avalanche.json
Adds wrapped AVAX in preparation for Avalanche
=> feat: add common Avalanche Tokens

package.json
publish new version that includes:
- base goerli tokens
- tokenMap object using new schema
=> feat: 11.3.0

.github/workflows/deploy.yaml, .github/workflows/tests.yaml, package.json, src/buildList.js, src/tokens/base.json, yarn.lock
=> feat: add base tokens

src/tokens/mainnet.json
https://uniswapteam.slack.com/archives/C04QKTF9T35/p1696464897559929
https://linear.app/uniswap/issue/DAT-145/add-token-request-celo-native-asset
=> Feat: Add celo native to eth list

package.json
=> bump up version to 11.7.0

package.json, src/tokens/optimism.json, src/tokens/polygon.json
https://docs.google.com/spreadsheets/d/1NQQNo8iOBxABHBSrFY0bnt5EeDk7v2-hP6ix8kj4IzQ/edit#gid=0 anything that was not already here!
=> feat: add new tokens

src/tokens/mainnet.json
https://uniswapteam.slack.com/archives/C014WRW57NJ/p1699035827179179
=> chore: Add celo wormholes l2s and change name

package.json, src/tokens/base.json
https://linear.app/uniswap/issue/DAT-218/default-token-list-addition-request-seamlesss
=> Feat: Add SEAM to base

package.json, src/tokens/arbitrum.json
https://linear.app/uniswap/issue/DAT-220/default-token-list-addition-request-magic
=> feat: Add magic to arbritrum

package.json, src/tokens/mainnet.json
https://linear.app/uniswap/issue/DAT-246/default-token-list-addition-request-gala
=> feat: Add GALA to supported token lsit

src/tokens/base.json, src/tokens/mainnet.json, src/tokens/optimism.json
https://linear.app/uniswap/issue/DAT-260/default-token-list-addition-request-ondo-finance
https://linear.app/uniswap/issue/DAT-261/default-token-list-addition-request-velodrome-finance
https://linear.app/uniswap/issue/DAT-262/default-token-list-addition-request-aerodrome-finance
=> feat: Add coins from slack

package.json, src/tokens/mainnet.json
https://etherscan.io/token/0xf091867EC603A6628eD83D274E835539D82e9cc8
https://linear.app/uniswap/issue/DAT-263/default-token-list-addition-request-zeta
=> Feat: Add zeta to default tokens

package.json, src/tokens/mainnet.json
https://linear.app/uniswap/issue/DAT-272/default-token-list-addition-request-usdc
=> feat: Add USDC native celo

package.json, src/tokens/mainnet.json
https://linear.app/uniswap/issue/DAT-275/default-token-list-addition-request-starknet
https://etherscan.io/token/0xca14007eff0db1f8135f4c25b34de49ab0d42766
=> feat: Add starknet

src/tokens/mainnet.json
https://www.coingecko.com/en/coins/galxe
=> fix: rename GAL token name from "Project Galaxy" to "Galxe"

package.json, src/tokens/celo.json, src/tokens/mainnet.json
https://linear.app/uniswap/issue/DAT-321/default-token-list-addition-request-usdt-on-celo
=> Feat: Add USDT for celo

package.json, src/tokens/mainnet.json
https://linear.app/uniswap/issue/DAT-326/default-token-list-addition-request-arkham
=> feat: Adding Arkham

package.json, src/tokens/mainnet.json
https://linear.app/uniswap/issue/DAT-344/default-token-list-addition-request-omni-network
https://linear.app/uniswap/issue/DAT-343/default-token-list-addition-request-beam
=> feat: Add more tokens

.github/workflows/deploy.yaml
Pulls the npm variable from the environment
=> fix: pull from npm env

package.json, src/tokens/mainnet.json
fixes DAT-440 DAT-441 DAT-442 DAT-443
=> add ethena, etherfi, altlayer, aevo

package.json, src/tokens/mainnet.json
adds PlayDapp (PDA) to the default token list
=> DAT-464 add PlayDapp PDA

package.json, src/tokens/mainnet.json
adds PORTAL to the default token list
=> DAT-470 Add portal token

.github/workflows/deploy.yaml
Sets the rungroup for the npm deploy job
=> ci: set npm rungroup

package.json, src/tokens/arbitrum.json, src/tokens/bnb.json, src/tokens/mainnet.json, src/tokens/optimism.json
=> chore: add kuji and pirate nation

package.json, src/tokens/mainnet.json
=> add FLOKI and REZ

.github/workflows/deploy.yaml
Fixes the broken indentation for yaml
=> fix: broken indentation

.github/workflows/deploy.yaml
Reverting temporarily to test monitors/alerts for failed deployments. Will re-revert.
=> Revert "fix: broken indentation"

.github/workflows/deploy.yaml
Automates the deploy action to run on main push. Still supports optional manual trigger.
=> Deploy on main push

package.json, src/tokens/base.json, src/tokens/mainnet.json
=> add blocklords, eurc

package.json, src/tokens/mainnet.json
adds Stader to mainnet
https://linear.app/uniswap/issue/DAT-576/default-token-list-addition-request-stader
=> chore: Dat-576 add stader

package.json, src/tokens/mainnet.json
=> chore: change euroc to eurc

package.json, src/tokens/mainnet.json
adds Layer3 to default list for mainnet
=> Chore: dat-585 add layer3

.github/workflows/deploy.yaml, package.json
=> chore: add provenance

.github/workflows/deploy.yaml
Creates write permissions for the gh action
=> chore(infra): write permissions for gh action

package.json, src/buildList.js, src/tokens/mainnet.json
=> add covalent token

package.json, src/tokens/mainnet.json
=> add gravity token

package.json, src/tokens/mainnet.json
- **add Syrup Tokenadd Aethir Tokenadd Apu Apustaja**
- **12.26.0**
=> add Syrup Token Aethir Token Apu Apustaja 2024 11 16 90

package.json, src/tokens/mainnet.json
- **add Morpho Tokenadd nulladd Quantoz EURQadd Quantoz USDQ**
- **12.28.0**
=> add Morpho Token null Quantoz EURQ Quantoz USDQ 2024 11 25 96

package.json, src/tokens/mainnet.json
- **add Movement**
- **12.30.0**
=> add Movement 2024 12 04 1

package.json, src/tokens/mainnet.json
=> add Neiro 2024 12 05 7

package.json, src/tokens/mainnet.json
=> add Swell 2024 11 27 68

package.json, src/tokens/mainnet.json
- **add SPX6900**
- **12.33.0**
=> add SPX6900 2024 12 16 73

package.json, src/tokens/base.json
- **add SPX6900**
- **12.33.0**
=> add SPX6900 2024 12 16 29

package.json, src/tokens/base.json
=> add Toshi 2025 01 22 65

package.json, src/tokens/base.json
- **add Venice Token**
- **13.2.0**
=> add Venice Token 2025 01 28 77

package.json, src/tokens/mainnet.json
=> add USUAL 2025 01 29 12

package.json, src/tokens/base.json, src/tokens/mainnet.json
- **add HarryPotterObamaSonic10Inu**
- **13.4.0**
=> add HarryPotterObamaSonic10Inu HarryPotterObamaSonic10Inu 2025 01 30 43

package.json, src/tokens/mainnet.json
- **add StablR USD**
- **13.4.0**
=> add StablR USD 2025 02 04 71

package.json, src/tokens/mainnet.json
- **add StablR Euro**
- **13.4.0**
=> add StablR Euro 2025 02 04 73

package.json, src/tokens/avalanche.json, src/tokens/mainnet.json
=> add Flux Flux null 2025 02 06 7

package.json, src/tokens/mainnet.json
=> add BIO 2025 02 06 84

package.json, src/tokens/base.json
=> add B3 2025 02 11 2

package.json, src/tokens/base.json
=> add KAITO 2025 02 26 44

package.json, src/tokens/mainnet.json
- **add Wrapped Analog One Token**
- **13.8.0**
=> add Wrapped Analog One Token 2025 02 26 60

package.json, src/tokens/optimism.json
=> add CYBER 2025 02 26 68

package.json, src/tokens/base.json
- **add aixbt by Virtuals**
- **13.7.0**
=> add aixbt by Virtuals 2025 02 26 22

package.json, src/tokens/base.json
- **add Odos Token**
- **13.7.0**
=> add Odos Token 2025 02 26 81

package.json, src/tokens/optimism.json
- **add Worldcoin**
- **13.12.0**
=> add Worldcoin 2025 03 11 83

package.json, src/tokens/base.json
- **add Cookie**
- **13.12.0**
=> add Cookie 2025 03 11 31

package.json, src/tokens/mainnet.json
- **add Redstone**
- **13.12.0**
=> add Redstone 2025 03 11 69

package.json, src/tokens/mainnet.json
- **add Liquid Staked ETH**
- **13.15.0**
=> add Liquid Staked ETH 2025 03 19 80

package.json, src/tokens/base.json
=> add FAI 2025 03 27 38

package.json, src/tokens/mainnet.json
- **add Pendle**
- **13.17.0**
=> add Pendle 2025 03 27 23

package.json, src/tokens/mainnet.json
- **add Schuman EUR P**
- **13.15.0**
=> add Schuman EUR P 2025 03 12 67

package.json, src/tokens/mainnet.json
=> add Corn 2025 04 01 86

package.json, src/tokens/mainnet.json
- **add Term Finance**
- **13.21.0**
=> add Term Finance 2025 04 01 30

package.json, src/tokens/base.json
- **add Keyboard Cat**
- **13.21.0**
=> add Keyboard Cat 2025 04 01 64

package.json, src/tokens/arbitrum.json
=> add Kinto 2025 04 04 27

package.json, src/tokens/base.json
- **add Definitive**
- **13.21.0**
=> add Definitive 2025 04 04 8

package.json, src/tokens/base.json
- **add Prompt**
- **13.29.0**
=> add Prompt 2025 04 14 56

package.json, src/tokens/base.json
=> add Zora 2025 04 29 37

package.json, src/tokens/mainnet.json
- **add KernelDAO**
- **13.30.0**
=> add KernelDAO 2025 04 23 18

package.json, src/tokens/base.json
- **add tokenbot**
- **13.30.0**
=> add tokenbot 2025 04 23 81

package.json, src/tokens/mainnet.json
- **add Mantle**
- **13.33.0**
=> add Mantle 2025 05 01 59

package.json, src/tokens/mainnet.json
- **add Space and Time**
- **13.34.0**
=> add Space and Time 2025 05 08 64

src/tokens/base.json, src/tokens/mainnet.json
https://uniswapteam.slack.com/archives/C014WRW57NJ/p1751307855644659
=> Add Default Tokens 6/30

package.json, src/tokens/mainnet.json
- **add Caldera**
- **13.38.0**
=> add Caldera 2025 07 18 96

package.json, src/tokens/base.json, src/tokens/mainnet.json
=> add Towns Horizen Mamo Succinct 2025 08 05 36

package.json, src/tokens/optimism.json
- **add WalletConnect**
- **13.43.0**
=> add WalletConnect 2025 08 14 82

package.json, src/tokens/base.json
- **add Sapien**
- **13.44.0**
=> add Sapien 2025 08 25 60
